### ISSUE TITLE
I would like to know if my complicated CSV is compatible with your configurated Chart.js

### ISSUE THREAD

**Issue by gusbemacbe** [dipeshdulal/pyramid_chart_example#1]
Namaskāra @dipeshdulal!

See my JSFIddle: https://jsfiddle.net/gusbemacbe/hogw83be/12/

- I use D3 and `date-fns`.
- I use a CSV file: you will check firstly the `istDeath` (`0` is survival and `1` is dead`), then person`s `sex` and finally the age. You can get the full CSV file:  https://gist.github.com/gusbemacbe/a1eab9d38641723cef447619c753f6c3
- The Chart.js did not recognise my CSV because they are objects and not arrays. I was recommended to use Loadsh. I do not know how to fix it. 

I checked your tutorial, I am not sure if my CSV file will work with your tutorial, because our Chart.js configurations are different, for example, `labels` will capture the `age` for y axis, while your `labels` captures the months. `data` of the first dataset captures the number of females grouped by age, and the second captures the number of males grouped by age. 

Is it compatible with your tutorial? 

Dhany'avāda!

Gustavo

**Comment by dipeshdulal** [comment]
@gusbemacbe 
I think you need to preprocess the data in the required format and modify the chart.js configuration as well. You cannot work with the configuration provided in the tutorial as the data set and axes are different.
